### ISSUE TITLE
Can't get Gulp to build

### ISSUE THREAD

**Issue by clubajax** [toranb/ember-lazy-loading-example#1]
Error: missing module import from js/app/app.js for path: ember/resolver. Looking in: ["/Users/../ember-lazy-loading-example"]

Everything else is found and it builds the dependencies, but I can't get it to resolve the ember path.

**Comment by toranb** [comment]
scumbad transpiler :)

https://github.com/toranb/ember-lazy-loading-example/commit/63b4849ed73d5b1aea67fcab737cad7fc636536e

Should be all good now -let me know if you find anything else

**Comment by clubajax** [comment]
Excellent. Works now!
